"Barcelona",
"Bayern Munchen",
"Real Madrid",
"Atletico Madrid",
"Juventus",
"Paris Saint Germain",
"Benfica",
"Borussia Dortmund",
"Roma",
"PSV Eindhoven",
"Leicester City",
"SSC Napoli",
"Manchester City",
"Arsenal",
"Sporting",
"Ajax",
"Bayer Leverkusen",
"Dynamo Kyiv",
"Tottenham Hotspur",
"Southampton",
"Athletic Bilbao",
"Olympiakos",
"Borussia Monchengladbach",
"Shakhtar Donetsk",
"FC Porto",
"Manchester United",
"Chelsea",
"Zenit St. Petersburg",
"Liverpool FC",
"Sevilla",
"Villarreal",
"Sparta Prague",
"Viktoria Plzen",
"Wolfsburg",
"Lyon",
"West Ham United",
"Monaco",
"Fiorentina",
"Schalke 04",
"Sassuolo",
"Inter Milan",
"Celta Vigo",
"Lille",
"Levadia Tallinn",
"Fenerbahce",
"Dnipro Dnipropetrovsk",
"Basel",
"Mainz 05",
"CSKA Moskva",
"Lazio",
"Celtic",
"Club Brugge",
"Real Sociedad",
"Nice",
"Besiktas",
"The New Saints",
"Flora Tallinn",
"Crvena Zvezda",
"Ludogorets Razgrad",
"AC Milan",
"Málaga",
"Swansea City",
"Dinamo Zagreb",
"FC Sheriff",
"FC Krasnodar",
"FC Red Bull Salzburg",
"Saint-Étienne",
"Nomme JK Kalju",
"Köln",
"BATE Borisov",
"APOEL Nicosia",
"Valencia",
"AZ Alkmaar",
"Feyenoord",
"Anderlecht",
"Everton FC",
"Sunderland",
"Rangers",
"Augsburg",
"Stoke City",
"Hertha Berlin",
"Werder Bremen",
"Olympique Marseille",
"Dundalk",
"Maribor",
"Dacia Chisinau",
"Genoa",
"Hamburger SV",
"Chievo Verona",
"Rosenborg",
"Rijeka",
"Torino",
"CSKA Sofia",
"Las Palmas",
"Litex Lovech",
"Omonia Nicosia",
"Montpellier",
"Lokomotiv Astana",
"Rayo Vallecano",
"Granada",
"Braga",
"Panathinaikos",
"Real Betis",
"Levski Sofia",
"Gent",
"Hoffenheim",
"Maccabi Tel Aviv",
"Partizan Beograd",
"West Brom Albion",
"Qarabağ",
"Ferencváros",
"Deportivo La Coruña",
"Espanyol",
"Elche",
"Atalanta",
"Sporting Gijón",
"Steaua Bucureşti",
"Freiburg",
"Newcastle United",
"Ingolstadt",
"Mladá Boleslav",
"Galatasaray",
"Trenčín",
"Young Boys",
"Empoli FC",
"København",
"Bordeaux",
"FK Rostov",
"Eintracht Frankfurt",
"Burnley",
"Malmö FF",
"Apollon Limassol",
"Lokomotiv Moskva",
"Legia Warszawa",
"Crystal Palace",
"Darmstadt",
"SC Bastia",
"Cork City",
"Rennes",
"Watford",
"AEK Larnaca",
"Vitesse",
"IFK Göteborg",
"Carpi",
"Zorya",
"Molde",
"İstanbul Başakşehir",
"Rapid Wien",
"Beroe",
"Guingamp",
"Sillamäe Kalev",
"Caen",
"Toulouse",
"PAOK Thessaloniki FC",
"Bologna",
"Spartak Moskva",
"Liberec",
"AIK",
"Genk",
"Olimpija Ljubljana",
"Astra Ploieşti",
"AFC Bournemouth",
"Wigan Athletic",
"Angers",
"FC Utrecht",
"Sampdoria",
"Palermo",
"Konyaspor",
"HJK Helsinki",
"Fehérvár",
"SD Eibar",
"Mallorca",
"Jablonec",
"Osasuna",
"Timişoara",
"FC Midtjylland",
"Getafe",
"Neath Athletic",
"VfB Stuttgart",
"Birmingham City",
"Vorskla",
"Shamrock Rovers",
"PEC Zwolle",
"Catania",
"Anorthosis",
"Lecce",
"Hull City",
"Lorient",
"İnter Bakı",
"Deportivo Xerez",
"Cagliari",
"Sochaux",
"Estoril",
"Valladolid",
"FC Twente",
"Aktobe",
"Strømsgodset",
"Blackburn Rovers",
"Arouca",
"Bolton Wanderers",
"Blackpool",
"",
"",
"Queens Park Rangers",
"Norwich City",
"Fulham",
"Reading",
"Portsmouth",
"Cardiff City",
"Wolverhampton Wanderers",
"Aston Villa",
"Austria Wien",
"Standard Liège",
"Hajduk Split",
"Fortuna Düsseldorf",
"Hannover 96",
"Maccabi Haifa",
"Udinese",
"Hellas Verona",
"Siena",
"Brescia",
"Parma",
"Frosinone",
"Bari",
"Cesena",
"Livorno",
"Rubin Kazan",
"Levante",
"Real Zaragoza",
"Tenerife",
"Almería",
"Hércules",
"Racing Santander",
"Slovan Bratislava",
"Žilina",
"Luzern",
"Trabzonspor",
"Sivasspor",
"Metalist Kharkiv",
"Los Angeles Galaxy",
"FC Dallas",
"Real Salt Lake",
"Guangzhou Evergrande",
"Sporting Kansas City",
"Boca Juniors",
"River Plate",
"Libertad",
"Corinthians",
"Atlético Nacional",
"Santos FC",
"Lanús",
"Estudiantes",
"Independiente",
"Grêmio",
"Atlético Mineiro",
"Rosario Central",
"Palmeiras",
"Racing Club",
"San Lorenzo",
"Guaraní",